# Generated by Django 4.1.1 on 2022-09-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('elementId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('url', models.CharField(max_length=255, null=True)),
                ('parentId', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=6)),
                ('size', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementId', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('url', models.CharField(max_length=255, null=True)),
                ('parentId', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=6)),
                ('size', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('elementId', 'date')},
            },
        ),
    ]
